### ISSUE TITLE
Requests are slowing down UI

### ISSUE THREAD

**Issue by mrkvon** [OpenHospitalityNetwork/sleepy-bike-solid#64]
User interface (UI) is very slow when data are fetched and processed. For example, open the sleepy.bike, go to "travel", and try to move the map while the accommodations are loading. It's going to be very slow, almost unresponsive.

**Comment by mrkvon** [comment]
Let's keep this open. While the #66 improved the situation somewhat, the map still freezes on slower devices, especially (older) phones. So we still have work to do on this one. 🙂

**Comment by mariha** [comment]
An index (#70) should fix it, or is there anything else that you think would need to be done here?

**Comment by mrkvon** [comment]
To be honest, the query system at the moment is very inefficient. It repeats a lot of work unnecessarily. We can improve that.

**Comment by dreirund** [comment]
> *User interface (UI) is very slow when data are fetched and processed.*

I have the same. CPU usage goes high, fan goes high. I am on a high-end laptop and still see lots of computing ressource usage.

Also, I see that loading the map pins takes a long time. I am on a ca. 200..500 kbps internet connection which, when used, has ping roundtrips of a few seconds. Maybe this makes the situatin even worse.

But in general the website seems not to be made with computation efficiency and technical barrier-freeness (poor internet connections, low end devices) in mind.

Regards!

**Comment by mrkvon** [comment]
Thank you for the feedback! It's much appreciated. It shows main pain points for you and other users, and helps us prioritize what to do next. :pray:

> in general the website seems not to be made with computation efficiency and technical barrier-freeness

Indeed, that's the next most important task to tackle. So far the challenge has been to just make it work. Now, with email notifications (hopefully) in place, we can move on to optimization and improving UX (user experience). It's still some way to go before sleepy.bike is pleasant to use.

**Comment by mrkvon** [comment]
Regarding the slowness, it's because we're fetching and processing linked data from many resources (many different pods of members). We also do it in rather inefficient way (repeating the already done processing unnecessarily many times), so there's plenty of room for improvement.

**Comment by mrkvon** [comment]
I believe this was resolved with geoindex introduced in #120. Please feel free to reopen if the issue remains.
